//
//Recipe.swift
//
//
/// The model for  a recipe.
///
/// This file was generated from JSON Schema using quicktype, do not modify it directly.
/// To parse the JSON, add this file to your project and do:
///
///   let recipeResponse = try? JSONDecoder().decode(RecipeResponse.self, from: jsonData)
///
///Code is generated by https://app.quicktype.io/
///
/// Sample data at the bottom comes from Edamam API website
///
import Foundation
import FirebaseFirestoreSwift

// MARK: - Recipe
///Add ID Property on Struct Fetched From JSON comes from this post: https://stackoverflow.com/questions/70998275/add-id-property-on-struct-fetched-from-json
struct Recipe: Codable, Identifiable, Equatable {
    static func == (lhs: Recipe, rhs: Recipe) -> Bool {
        lhs.uri == rhs.uri &&
        lhs.label == rhs.label
    }
    //@DocumentID var id: String?
    var id: String? = UUID().uuidString
    let uri: String
    let label: String
    let image: String
    let images: Images
    let source: String
    let url: String
    let shareAs: String
    let yield: Double
    let dietLabels, healthLabels, cautions, ingredientLines: [String]
    let ingredients: [Ingredient]
    let calories, totalCO2Emissions,totalWeight: Double
    let co2EmissionsClass: String
    let totalTime: Int
    let cuisineType, mealType, dishType: [String]
    let totalNutrients, totalDaily: [String: Total]
    let digest: [Digest]
    
    enum CodingKeys: String, CodingKey {
        //case id
        case uri, label, image, source, url, shareAs
        case images
        case yield
        case totalTime
        case dietLabels, healthLabels, cautions, ingredientLines, cuisineType, mealType, dishType
        case ingredients
        case calories, totalCO2Emissions,totalWeight
        case co2EmissionsClass
        case totalNutrients, totalDaily
        case digest
       }
    
    static func sample(index: Int) -> Recipe {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let jsonData = recipeResponseJson.data(using: .utf8)!
        let recipe:RecipeResponse = try! decoder.decode(RecipeResponse.self, from: jsonData)
        return recipe.hits[index].recipe
    }
    
    
    var mainCuisineType: String {
        return cuisineType[0]
    }
    
    func equalTo(_ anotherRecipe: Recipe) -> Bool {
        if uri == anotherRecipe.uri &&
            label == anotherRecipe.label &&
            url == anotherRecipe.url &&
            image == anotherRecipe.image {
            return true
        } else {
            return false
        }
    }
}

// add this to make your struct conform to Hashable
extension Recipe: Hashable {
    func hash(into hasher: inout Hasher) {
        hasher.combine(uri)
        hasher.combine(label)
        hasher.combine(url)
        hasher.combine(image)
    }
}

// MARK: - Digest
struct Digest: Codable {
    let label, tag: String
    let schemaOrgTag: String?
    let total: Double
    let hasRDI: Bool
    let daily: Double
    let unit: Unit
    let sub: [Digest]?
}

enum Unit: String, Codable {
    case empty = "%"
    case g = "g"
    case kcal = "kcal"
    case mg = "mg"
    case µg = "µg"
}

// MARK: - Images
struct Images: Codable {
    let thumbnail, small, regular: Large
    let large: Large?

    enum CodingKeys: String, CodingKey {
        case thumbnail = "THUMBNAIL"
        case small = "SMALL"
        case regular = "REGULAR"
        case large = "LARGE"
    }
}

// MARK: - Large
struct Large: Codable {
    let url: String
    let width, height: Int
}

// MARK: - Ingredient
struct Ingredient: Codable,Identifiable {
    let id = UUID()
    let text: String
    let quantity: Double
    let measure: String?
    let food: String
    let weight: Double
    let foodCategory: String?
    let foodID: String
    let image: String?

    enum CodingKeys: String, CodingKey {
        case text, quantity, measure, food, weight, foodCategory
        case foodID = "foodId"
        case image
    }
}

// MARK: - Total
struct Total: Codable {
    let label: String
    let quantity: Double
    let unit: Unit
}

// MARK: - RecipeResponseLinks
struct RecipeResponseLinks: Codable {
}


///////////////////////////////////////////////
///Testing purpose


// MARK: - RecipeResponse
struct RecipeResponse: Codable {
    let from, to, count: Int
    let links: RecipeResponseLinks
    let hits: [Hit]

    enum CodingKeys: String, CodingKey {
        case from, to, count
        case links = "_links"
        case hits
    }
    
    static func sample() -> RecipeResponse {
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        let jsonData = recipeResponseJson.data(using: .utf8)!
        let recipe:RecipeResponse = try! decoder.decode(RecipeResponse.self, from: jsonData)
        return recipe
    }
    
    static func empty() -> RecipeResponse {
        return RecipeResponse(from: 0, to: 0, count: 0, links: RecipeResponseLinks(), hits: [Hit]())
    }
}

// MARK: - Hit
struct Hit: Codable, Identifiable {
    let id = UUID()
    
    let recipe: Recipe
    let links: HitLinks

    enum CodingKeys: String, CodingKey {
        case recipe
        case links = "_links"
    }
}

// MARK: - HitLinks
struct HitLinks: Codable {
    let linksSelf: Next

    enum CodingKeys: String, CodingKey {
        case linksSelf = "self"
    }
}

// MARK: - Next
struct Next: Codable {
    let href: String
    let title: Title
}

enum Title: String, Codable {
    case nextPage = "Next page"
    case titleSelf = "Self"
}

let recipeResponseJson = """

{
  "from": 1,
  "to": 3,
  "count": 3,
  "_links": {},
  "hits": [
    {
      "recipe": {
        "uri": "http://www.edamam.com/ontologies/edamam.owl#recipe_a4c8d32778076ed839cf5d4840793ac3",
        "label": "Crawfish Etouffee",
        "image": "https://edamam-product-images.s3.amazonaws.com/web-img/1a5/1a5e5b32a6089e6675e11634874547b6?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=2be46bfef178b0451d33dfe182d0c895c4a870fa6eae38c4b71de0543dd10cfc",
        "images": {
          "THUMBNAIL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/1a5/1a5e5b32a6089e6675e11634874547b6-s?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=eb0860d065de8da59ef35317e7b5216370ee546b46454f7dd079403a740b2f84",
            "width": 100,
            "height": 100
          },
          "SMALL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/1a5/1a5e5b32a6089e6675e11634874547b6-m?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=941a1aca0b7be4407eecbe2929cab3376f25f63c52cfa22cd9044354a3da89e0",
            "width": 200,
            "height": 200
          },
          "REGULAR": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/1a5/1a5e5b32a6089e6675e11634874547b6?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=2be46bfef178b0451d33dfe182d0c895c4a870fa6eae38c4b71de0543dd10cfc",
            "width": 300,
            "height": 300
          }
        },
        "source": "justapinch.com",
        "url": "https://www.justapinch.com/recipes/main-course/french/crawfish-etouffee.html",
        "shareAs": "http://www.edamam.com/recipe/crawfish-etouffee-a4c8d32778076ed839cf5d4840793ac3/crawfish+etouffee/5-8-ing/high-protein/100-300-cal",
        "yield": 6,
        "dietLabels": [
          "High-Protein",
          "Low-Carb"
        ],
        "healthLabels": [
          "Sugar-Conscious",
          "Pescatarian",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Soy-Free",
          "Fish-Free",
          "Pork-Free",
          "Red-Meat-Free",
          "Celery-Free",
          "Mustard-Free",
          "Sesame-Free",
          "Lupine-Free",
          "Mollusk-Free",
          "Alcohol-Free",
          "Sulfite-Free"
        ],
        "cautions": [
          "Sulfites"
        ],
        "ingredientLines": [
          "2 lb crawfish tails",
          "2 can(s) cream of mushroom soup, golden",
          "1 bunch green onion",
          "1/2 bunch parsley",
          "1 clove garlic",
          "· salt, pepper, red pepper"
        ],
        "ingredients": [
          {
            "text": "2 lb crawfish tails",
            "quantity": 2,
            "measure": "pound",
            "food": "crawfish",
            "weight": 907.18474,
            "foodCategory": "seafood",
            "foodId": "food_as9lwx2a9gc0lgb6rwtk5afip7ot",
            "image": "https://www.edamam.com/food-img/3cf/3cf27bacbfc6b38f999fbe2bb2840d8f.jpg"
          },
          {
            "text": "2 can(s) cream of mushroom soup, golden",
            "quantity": 2,
            "measure": "can",
            "food": "cream of mushroom soup",
            "weight": 606,
            "foodCategory": "canned soup",
            "foodId": "food_b628l7bbpw7rnqa1ri8egb0xetpn",
            "image": "https://www.edamam.com/food-img/545/545d0db4311588977bed0aabfa530c58.jpg"
          },
          {
            "text": "1 bunch green onion",
            "quantity": 1,
            "measure": "bunch",
            "food": "green onion",
            "weight": 113,
            "foodCategory": "vegetables",
            "foodId": "food_bknlkyzbuzo27pb11whr4bttkuy6",
            "image": "https://www.edamam.com/food-img/b89/b89986ed6aa466285bdd99bac34b3c46.jpg"
          },
          {
            "text": "1/2 bunch parsley",
            "quantity": 0.5,
            "measure": "bunch",
            "food": "parsley",
            "weight": 30,
            "foodCategory": "vegetables",
            "foodId": "food_b244pqdazw24zobr5vqu2bf0uid8",
            "image": "https://www.edamam.com/food-img/46a/46a132e96626d7989b4d6ed8c91f4da0.jpg"
          },
          {
            "text": "1 clove garlic",
            "quantity": 1,
            "measure": "clove",
            "food": "garlic",
            "weight": 3,
            "foodCategory": "vegetables",
            "foodId": "food_avtcmx6bgjv1jvay6s6stan8dnyp",
            "image": "https://www.edamam.com/food-img/6ee/6ee142951f48aaf94f4312409f8d133d.jpg"
          },
          {
            "text": "· salt, pepper, red pepper",
            "quantity": 0,
            "measure": null,
            "food": "salt",
            "weight": 9.955108440000002,
            "foodCategory": "Condiments and sauces",
            "foodId": "food_btxz81db72hwbra2pncvebzzzum9",
            "image": "https://www.edamam.com/food-img/694/6943ea510918c6025795e8dc6e6eaaeb.jpg"
          }
        ],
        "calories": 1228.7022498000001,
        "totalWeight": 1659.1847400000001,
        "totalTime": 140,
        "cuisineType": [
          "american"
        ],
        "mealType": [
          "lunch/dinner"
        ],
        "dishType": [
          "starter"
        ],
        "totalNutrients": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 1228.7022498000001,
            "unit": "kcal"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 41.202955030000005,
            "unit": "g"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 7.362693736600001,
            "unit": "g"
          },
          "FATRN": {
            "label": "Trans",
            "quantity": 0.13938,
            "unit": "g"
          },
          "FAMS": {
            "label": "Monounsaturated",
            "quantity": 9.0849814476,
            "unit": "g"
          },
          "FAPU": {
            "label": "Polyunsaturated",
            "quantity": 20.3664012882,
            "unit": "g"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 52.393,
            "unit": "g"
          },
          "CHOCDF.net": {
            "label": "Carbohydrates (net)",
            "quantity": 44.16,
            "unit": "g"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 8.233,
            "unit": "g"
          },
          "SUGAR": {
            "label": "Sugars",
            "quantity": 5.341900000000001,
            "unit": "g"
          },
          "SUGAR.added": {
            "label": "Sugars, added",
            "quantity": 0,
            "unit": "g"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 156.20810297800003,
            "unit": "g"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 1034.1906036,
            "unit": "mg"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 4749.0171492,
            "unit": "mg"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 445.84987979999994,
            "unit": "mg"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 301.46987980000006,
            "unit": "mg"
          },
          "K": {
            "label": "Potassium",
            "quantity": 3617.6479148000008,
            "unit": "mg"
          },
          "FE": {
            "label": "Iron",
            "quantity": 12.294551816,
            "unit": "mg"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 13.256501620000005,
            "unit": "mg"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 2531.6329344000005,
            "unit": "mg"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 340.0695584,
            "unit": "µg"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 72.96621688000002,
            "unit": "mg"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 0.8016993180000003,
            "unit": "mg"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 0.5103591168,
            "unit": "mg"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 23.129489059200004,
            "unit": "mg"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 1.2036395192,
            "unit": "mg"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 465.7883538,
            "unit": "µg"
          },
          "FOLFD": {
            "label": "Folate (food)",
            "quantity": 465.7883538,
            "unit": "µg"
          },
          "FOLAC": {
            "label": "Folic acid",
            "quantity": 0,
            "unit": "µg"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 18.143694800000002,
            "unit": "µg"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 1.2120000000000002,
            "unit": "µg"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 29.73366509000001,
            "unit": "mg"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 845.6441847400001,
            "unit": "µg"
          },
          "Sugar.alcohol": {
            "label": "Sugar alcohol",
            "quantity": 0,
            "unit": "g"
          },
          "WATER": {
            "label": "Water",
            "quantity": 1388.9290301760002,
            "unit": "g"
          }
        },
        "totalDaily": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 61.43511249000001,
            "unit": "%"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 63.38916158461539,
            "unit": "%"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 36.813468683,
            "unit": "%"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 17.464333333333332,
            "unit": "%"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 32.932,
            "unit": "%"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 312.41620595600006,
            "unit": "%"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 344.7302012,
            "unit": "%"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 197.87571455,
            "unit": "%"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 44.584987979999994,
            "unit": "%"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 71.77854280952383,
            "unit": "%"
          },
          "K": {
            "label": "Potassium",
            "quantity": 76.97123222978725,
            "unit": "%"
          },
          "FE": {
            "label": "Iron",
            "quantity": 68.30306564444444,
            "unit": "%"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 120.51365109090915,
            "unit": "%"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 361.6618477714286,
            "unit": "%"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 37.78550648888889,
            "unit": "%"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 81.07357431111113,
            "unit": "%"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 66.80827650000003,
            "unit": "%"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 39.2583936,
            "unit": "%"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 144.55930662000003,
            "unit": "%"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 92.58765532307693,
            "unit": "%"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 116.44708845,
            "unit": "%"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 755.9872833333335,
            "unit": "%"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 8.080000000000002,
            "unit": "%"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 198.2244339333334,
            "unit": "%"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 704.7034872833334,
            "unit": "%"
          }
        },
        "digest": [
          {
            "label": "Fat",
            "tag": "FAT",
            "schemaOrgTag": "fatContent",
            "total": 41.202955030000005,
            "hasRDI": true,
            "daily": 63.38916158461539,
            "unit": "g",
            "sub": [
              {
                "label": "Saturated",
                "tag": "FASAT",
                "schemaOrgTag": "saturatedFatContent",
                "total": 7.362693736600001,
                "hasRDI": true,
                "daily": 36.813468683,
                "unit": "g"
              },
              {
                "label": "Trans",
                "tag": "FATRN",
                "schemaOrgTag": "transFatContent",
                "total": 0.13938,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Monounsaturated",
                "tag": "FAMS",
                "schemaOrgTag": null,
                "total": 9.0849814476,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Polyunsaturated",
                "tag": "FAPU",
                "schemaOrgTag": null,
                "total": 20.3664012882,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Carbs",
            "tag": "CHOCDF",
            "schemaOrgTag": "carbohydrateContent",
            "total": 52.393,
            "hasRDI": true,
            "daily": 17.464333333333332,
            "unit": "g",
            "sub": [
              {
                "label": "Carbs (net)",
                "tag": "CHOCDF.net",
                "schemaOrgTag": null,
                "total": 44.16,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Fiber",
                "tag": "FIBTG",
                "schemaOrgTag": "fiberContent",
                "total": 8.233,
                "hasRDI": true,
                "daily": 32.932,
                "unit": "g"
              },
              {
                "label": "Sugars",
                "tag": "SUGAR",
                "schemaOrgTag": "sugarContent",
                "total": 5.341900000000001,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Sugars, added",
                "tag": "SUGAR.added",
                "schemaOrgTag": null,
                "total": 0,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Protein",
            "tag": "PROCNT",
            "schemaOrgTag": "proteinContent",
            "total": 156.20810297800003,
            "hasRDI": true,
            "daily": 312.41620595600006,
            "unit": "g"
          },
          {
            "label": "Cholesterol",
            "tag": "CHOLE",
            "schemaOrgTag": "cholesterolContent",
            "total": 1034.1906036,
            "hasRDI": true,
            "daily": 344.7302012,
            "unit": "mg"
          },
          {
            "label": "Sodium",
            "tag": "NA",
            "schemaOrgTag": "sodiumContent",
            "total": 4749.0171492,
            "hasRDI": true,
            "daily": 197.87571455,
            "unit": "mg"
          },
          {
            "label": "Calcium",
            "tag": "CA",
            "schemaOrgTag": null,
            "total": 445.84987979999994,
            "hasRDI": true,
            "daily": 44.584987979999994,
            "unit": "mg"
          },
          {
            "label": "Magnesium",
            "tag": "MG",
            "schemaOrgTag": null,
            "total": 301.46987980000006,
            "hasRDI": true,
            "daily": 71.77854280952383,
            "unit": "mg"
          },
          {
            "label": "Potassium",
            "tag": "K",
            "schemaOrgTag": null,
            "total": 3617.6479148000008,
            "hasRDI": true,
            "daily": 76.97123222978725,
            "unit": "mg"
          },
          {
            "label": "Iron",
            "tag": "FE",
            "schemaOrgTag": null,
            "total": 12.294551816,
            "hasRDI": true,
            "daily": 68.30306564444444,
            "unit": "mg"
          },
          {
            "label": "Zinc",
            "tag": "ZN",
            "schemaOrgTag": null,
            "total": 13.256501620000005,
            "hasRDI": true,
            "daily": 120.51365109090915,
            "unit": "mg"
          },
          {
            "label": "Phosphorus",
            "tag": "P",
            "schemaOrgTag": null,
            "total": 2531.6329344000005,
            "hasRDI": true,
            "daily": 361.6618477714286,
            "unit": "mg"
          },
          {
            "label": "Vitamin A",
            "tag": "VITA_RAE",
            "schemaOrgTag": null,
            "total": 340.0695584,
            "hasRDI": true,
            "daily": 37.78550648888889,
            "unit": "µg"
          },
          {
            "label": "Vitamin C",
            "tag": "VITC",
            "schemaOrgTag": null,
            "total": 72.96621688000002,
            "hasRDI": true,
            "daily": 81.07357431111113,
            "unit": "mg"
          },
          {
            "label": "Thiamin (B1)",
            "tag": "THIA",
            "schemaOrgTag": null,
            "total": 0.8016993180000003,
            "hasRDI": true,
            "daily": 66.80827650000003,
            "unit": "mg"
          },
          {
            "label": "Riboflavin (B2)",
            "tag": "RIBF",
            "schemaOrgTag": null,
            "total": 0.5103591168,
            "hasRDI": true,
            "daily": 39.2583936,
            "unit": "mg"
          },
          {
            "label": "Niacin (B3)",
            "tag": "NIA",
            "schemaOrgTag": null,
            "total": 23.129489059200004,
            "hasRDI": true,
            "daily": 144.55930662000003,
            "unit": "mg"
          },
          {
            "label": "Vitamin B6",
            "tag": "VITB6A",
            "schemaOrgTag": null,
            "total": 1.2036395192,
            "hasRDI": true,
            "daily": 92.58765532307693,
            "unit": "mg"
          },
          {
            "label": "Folate equivalent (total)",
            "tag": "FOLDFE",
            "schemaOrgTag": null,
            "total": 465.7883538,
            "hasRDI": true,
            "daily": 116.44708845,
            "unit": "µg"
          },
          {
            "label": "Folate (food)",
            "tag": "FOLFD",
            "schemaOrgTag": null,
            "total": 465.7883538,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Folic acid",
            "tag": "FOLAC",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Vitamin B12",
            "tag": "VITB12",
            "schemaOrgTag": null,
            "total": 18.143694800000002,
            "hasRDI": true,
            "daily": 755.9872833333335,
            "unit": "µg"
          },
          {
            "label": "Vitamin D",
            "tag": "VITD",
            "schemaOrgTag": null,
            "total": 1.2120000000000002,
            "hasRDI": true,
            "daily": 8.080000000000002,
            "unit": "µg"
          },
          {
            "label": "Vitamin E",
            "tag": "TOCPHA",
            "schemaOrgTag": null,
            "total": 29.73366509000001,
            "hasRDI": true,
            "daily": 198.2244339333334,
            "unit": "mg"
          },
          {
            "label": "Vitamin K",
            "tag": "VITK1",
            "schemaOrgTag": null,
            "total": 845.6441847400001,
            "hasRDI": true,
            "daily": 704.7034872833334,
            "unit": "µg"
          },
          {
            "label": "Sugar alcohols",
            "tag": "Sugar.alcohol",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          },
          {
            "label": "Water",
            "tag": "WATER",
            "schemaOrgTag": null,
            "total": 1388.9290301760002,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          }
        ]
      },
      "_links": {
        "self": {
          "title": "Self",
          "href": "https://api.edamam.com/api/recipes/v2/a4c8d32778076ed839cf5d4840793ac3?type=public&app_id=60774aad&app_key=4ed5ca518b3756cbc0701d7501264aa8"
        }
      }
    },
    {
      "recipe": {
        "uri": "http://www.edamam.com/ontologies/edamam.owl#recipe_b4bc51b8a9300f7469afe21fe70207f7",
        "label": "Crawfish Etouffee",
        "image": "https://edamam-product-images.s3.amazonaws.com/web-img/06f/06fcb49281c4a1ee8d1529a23a249b1f.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2149e7a243b8fea66d818ddf5f7a095ac2ad3e8a29d2d11a90b4d6d7d980604",
        "images": {
          "THUMBNAIL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/06f/06fcb49281c4a1ee8d1529a23a249b1f-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=6c343d5000e4135ddbb5369aec53e4292abc70f2df653b08aabefb98e9baf0f9",
            "width": 100,
            "height": 100
          },
          "SMALL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/06f/06fcb49281c4a1ee8d1529a23a249b1f-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=aa067cbef39e0ec05f3698d0dcb05fc49e480c86fce490c56c3ecd4517ce31a0",
            "width": 200,
            "height": 200
          },
          "REGULAR": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/06f/06fcb49281c4a1ee8d1529a23a249b1f.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c2149e7a243b8fea66d818ddf5f7a095ac2ad3e8a29d2d11a90b4d6d7d980604",
            "width": 300,
            "height": 300
          },
          "LARGE": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/06f/06fcb49281c4a1ee8d1529a23a249b1f-l.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=d85242eecf4957d1c3041dc2df768c19f30ed9c02bdcc9e9c29d87e2aed053a9",
            "width": 600,
            "height": 600
          }
        },
        "source": "geauxaskalice.com",
        "url": "https://geauxaskalice.com/crawfish-etouffee/",
        "shareAs": "http://www.edamam.com/recipe/crawfish-etouffee-b4bc51b8a9300f7469afe21fe70207f7/crawfish+etouffee/5-8-ing/high-protein/100-300-cal",
        "yield": 14,
        "dietLabels": [
          "High-Protein",
          "Low-Carb"
        ],
        "healthLabels": [
          "Sugar-Conscious",
          "Keto-Friendly",
          "Pescatarian",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Soy-Free",
          "Fish-Free",
          "Pork-Free",
          "Red-Meat-Free",
          "Mustard-Free",
          "Sesame-Free",
          "Lupine-Free",
          "Mollusk-Free",
          "Alcohol-Free",
          "Sulfite-Free"
        ],
        "cautions": [
          "Sulfites"
        ],
        "ingredientLines": [
          "6-8 lbs. crawfish tails",
          "1 stick butter",
          "2-16 oz. containers of pre-chopped onion mixture",
          "1 T. minced garlic",
          "1 small can tomato paste",
          "1 can cream of mushroom soup",
          "1 can of celery soup",
          "1 bunch chopped green onions"
        ],
        "ingredients": [
          {
            "text": "6-8 lbs. crawfish tails",
            "quantity": 7,
            "measure": "pound",
            "food": "crawfish",
            "weight": 3175.1465900000003,
            "foodCategory": "seafood",
            "foodId": "food_as9lwx2a9gc0lgb6rwtk5afip7ot",
            "image": "https://www.edamam.com/food-img/3cf/3cf27bacbfc6b38f999fbe2bb2840d8f.jpg"
          },
          {
            "text": "1 stick butter",
            "quantity": 1,
            "measure": "stick",
            "food": "butter",
            "weight": 113,
            "foodCategory": "Dairy",
            "foodId": "food_awz3iefajbk1fwahq9logahmgltj",
            "image": "https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg"
          },
          {
            "text": "2-16 oz. containers of pre-chopped onion mixture",
            "quantity": 9,
            "measure": "ounce",
            "food": "onion",
            "weight": 255.145708125,
            "foodCategory": "vegetables",
            "foodId": "food_bmrvi4ob4binw9a5m7l07amlfcoy",
            "image": "https://www.edamam.com/food-img/205/205e6bf2399b85d34741892ef91cc603.jpg"
          },
          {
            "text": "1 T. minced garlic",
            "quantity": 1,
            "measure": "teaspoon",
            "food": "garlic",
            "weight": 2.8,
            "foodCategory": "vegetables",
            "foodId": "food_avtcmx6bgjv1jvay6s6stan8dnyp",
            "image": "https://www.edamam.com/food-img/6ee/6ee142951f48aaf94f4312409f8d133d.jpg"
          },
          {
            "text": "1 small can tomato paste",
            "quantity": 1,
            "measure": "can",
            "food": "tomato paste",
            "weight": 170,
            "foodCategory": "canned vegetables",
            "foodId": "food_auu2atfal07b6gbd1a5wsawy7u0s",
            "image": "https://www.edamam.com/food-img/aef/aef4e029118da71388e526086506053a.jpg"
          },
          {
            "text": "1 can cream of mushroom soup",
            "quantity": 1,
            "measure": "can",
            "food": "cream of mushroom soup",
            "weight": 303,
            "foodCategory": "canned soup",
            "foodId": "food_b628l7bbpw7rnqa1ri8egb0xetpn",
            "image": "https://www.edamam.com/food-img/545/545d0db4311588977bed0aabfa530c58.jpg"
          },
          {
            "text": "1 can of celery soup",
            "quantity": 1,
            "measure": "<unit>",
            "food": "celery",
            "weight": 40,
            "foodCategory": "vegetables",
            "foodId": "food_bffeoksbyyur8ja4da73ub2xs57g",
            "image": "https://www.edamam.com/food-img/d91/d91d2aed1c36d8fad54c4d7dc58f5a18.jpg"
          },
          {
            "text": "1 bunch chopped green onions",
            "quantity": 1,
            "measure": "bunch",
            "food": "green onions",
            "weight": 113,
            "foodCategory": "vegetables",
            "foodId": "food_bknlkyzbuzo27pb11whr4bttkuy6",
            "image": "https://www.edamam.com/food-img/b89/b89986ed6aa466285bdd99bac34b3c46.jpg"
          }
        ],
        "calories": 3782.6331575500003,
        "totalWeight": 4172.0922981250005,
        "totalTime": 0,
        "cuisineType": [
          "chinese"
        ],
        "mealType": [
          "lunch/dinner"
        ],
        "dishType": [
          "starter"
        ],
        "totalNutrients": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 3782.63315755,
            "unit": "kcal"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 139.228038313125,
            "unit": "g"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 66.3478562755125,
            "unit": "g"
          },
          "FATRN": {
            "label": "Trans",
            "quantity": 3.7738300000000002,
            "unit": "g"
          },
          "FAMS": {
            "label": "Monounsaturated",
            "quantity": 33.16274200865625,
            "unit": "g"
          },
          "FAPU": {
            "label": "Polyunsaturated",
            "quantity": 21.96766627908125,
            "unit": "g"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 87.057289138875,
            "unit": "g"
          },
          "CHOCDF.net": {
            "label": "Carbohydrates (net)",
            "quantity": 69.99201210075,
            "unit": "g"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 17.065277038125,
            "unit": "g"
          },
          "SUGAR": {
            "label": "Sugars",
            "quantity": 36.000878024500004,
            "unit": "g"
          },
          "SUGAR.added": {
            "label": "Sugars, added",
            "quantity": 0,
            "unit": "g"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 524.7944932123751,
            "unit": "g"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 3862.6171126000004,
            "unit": "mg"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 5351.506850525,
            "unit": "mg"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 1143.0810921687503,
            "unit": "mg"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 993.2541501125002,
            "unit": "mg"
          },
          "K": {
            "label": "Potassium",
            "quantity": 12333.4034356625,
            "unit": "mg"
          },
          "FE": {
            "label": "Iron",
            "quantity": 34.6410373430625,
            "unit": "mg"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 43.741833373812504,
            "unit": "mg"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 8499.00152575625,
            "unit": "mg"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 1481.5034544,
            "unit": "µg"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 117.57014148124998,
            "unit": "mg"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 2.5601296387375,
            "unit": "mg"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 1.5482162499937504,
            "unit": "mg"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 77.46606572862501,
            "unit": "mg"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 4.28448316695,
            "unit": "mg"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 1339.9359228437504,
            "unit": "µg"
          },
          "FOLFD": {
            "label": "Folate (food)",
            "quantity": 1339.9359228437504,
            "unit": "µg"
          },
          "FOLAC": {
            "label": "Folic acid",
            "quantity": 0,
            "unit": "µg"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 63.69503180000001,
            "unit": "µg"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 2.301,
            "unit": "µg"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 102.72104695662502,
            "unit": "mg"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 336.55132942250003,
            "unit": "µg"
          },
          "Sugar.alcohol": {
            "label": "Sugar alcohol",
            "quantity": 0,
            "unit": "g"
          },
          "WATER": {
            "label": "Water",
            "quantity": 3381.784236126188,
            "unit": "g"
          }
        },
        "totalDaily": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 189.1316578775,
            "unit": "%"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 214.19698202019234,
            "unit": "%"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 331.73928137756246,
            "unit": "%"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 29.019096379625,
            "unit": "%"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 68.2611081525,
            "unit": "%"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 1049.5889864247501,
            "unit": "%"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 1287.5390375333334,
            "unit": "%"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 222.97945210520834,
            "unit": "%"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 114.30810921687504,
            "unit": "%"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 236.4890833601191,
            "unit": "%"
          },
          "K": {
            "label": "Potassium",
            "quantity": 262.4128390566489,
            "unit": "%"
          },
          "FE": {
            "label": "Iron",
            "quantity": 192.45020746145832,
            "unit": "%"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 397.6530306710228,
            "unit": "%"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 1214.1430751080356,
            "unit": "%"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 164.61149493333335,
            "unit": "%"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 130.6334905347222,
            "unit": "%"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 213.34413656145833,
            "unit": "%"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 119.09355769182696,
            "unit": "%"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 484.1629108039063,
            "unit": "%"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 329.5756282269231,
            "unit": "%"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 334.9839807109376,
            "unit": "%"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 2653.9596583333337,
            "unit": "%"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 15.340000000000002,
            "unit": "%"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 684.8069797108334,
            "unit": "%"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 280.4594411854167,
            "unit": "%"
          }
        },
        "digest": [
          {
            "label": "Fat",
            "tag": "FAT",
            "schemaOrgTag": "fatContent",
            "total": 139.228038313125,
            "hasRDI": true,
            "daily": 214.19698202019234,
            "unit": "g",
            "sub": [
              {
                "label": "Saturated",
                "tag": "FASAT",
                "schemaOrgTag": "saturatedFatContent",
                "total": 66.3478562755125,
                "hasRDI": true,
                "daily": 331.73928137756246,
                "unit": "g"
              },
              {
                "label": "Trans",
                "tag": "FATRN",
                "schemaOrgTag": "transFatContent",
                "total": 3.7738300000000002,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Monounsaturated",
                "tag": "FAMS",
                "schemaOrgTag": null,
                "total": 33.16274200865625,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Polyunsaturated",
                "tag": "FAPU",
                "schemaOrgTag": null,
                "total": 21.96766627908125,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Carbs",
            "tag": "CHOCDF",
            "schemaOrgTag": "carbohydrateContent",
            "total": 87.057289138875,
            "hasRDI": true,
            "daily": 29.019096379625,
            "unit": "g",
            "sub": [
              {
                "label": "Carbs (net)",
                "tag": "CHOCDF.net",
                "schemaOrgTag": null,
                "total": 69.99201210075,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Fiber",
                "tag": "FIBTG",
                "schemaOrgTag": "fiberContent",
                "total": 17.065277038125,
                "hasRDI": true,
                "daily": 68.2611081525,
                "unit": "g"
              },
              {
                "label": "Sugars",
                "tag": "SUGAR",
                "schemaOrgTag": "sugarContent",
                "total": 36.000878024500004,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Sugars, added",
                "tag": "SUGAR.added",
                "schemaOrgTag": null,
                "total": 0,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Protein",
            "tag": "PROCNT",
            "schemaOrgTag": "proteinContent",
            "total": 524.7944932123751,
            "hasRDI": true,
            "daily": 1049.5889864247501,
            "unit": "g"
          },
          {
            "label": "Cholesterol",
            "tag": "CHOLE",
            "schemaOrgTag": "cholesterolContent",
            "total": 3862.6171126000004,
            "hasRDI": true,
            "daily": 1287.5390375333334,
            "unit": "mg"
          },
          {
            "label": "Sodium",
            "tag": "NA",
            "schemaOrgTag": "sodiumContent",
            "total": 5351.506850525,
            "hasRDI": true,
            "daily": 222.97945210520834,
            "unit": "mg"
          },
          {
            "label": "Calcium",
            "tag": "CA",
            "schemaOrgTag": null,
            "total": 1143.0810921687503,
            "hasRDI": true,
            "daily": 114.30810921687504,
            "unit": "mg"
          },
          {
            "label": "Magnesium",
            "tag": "MG",
            "schemaOrgTag": null,
            "total": 993.2541501125002,
            "hasRDI": true,
            "daily": 236.4890833601191,
            "unit": "mg"
          },
          {
            "label": "Potassium",
            "tag": "K",
            "schemaOrgTag": null,
            "total": 12333.4034356625,
            "hasRDI": true,
            "daily": 262.4128390566489,
            "unit": "mg"
          },
          {
            "label": "Iron",
            "tag": "FE",
            "schemaOrgTag": null,
            "total": 34.6410373430625,
            "hasRDI": true,
            "daily": 192.45020746145832,
            "unit": "mg"
          },
          {
            "label": "Zinc",
            "tag": "ZN",
            "schemaOrgTag": null,
            "total": 43.741833373812504,
            "hasRDI": true,
            "daily": 397.6530306710228,
            "unit": "mg"
          },
          {
            "label": "Phosphorus",
            "tag": "P",
            "schemaOrgTag": null,
            "total": 8499.00152575625,
            "hasRDI": true,
            "daily": 1214.1430751080356,
            "unit": "mg"
          },
          {
            "label": "Vitamin A",
            "tag": "VITA_RAE",
            "schemaOrgTag": null,
            "total": 1481.5034544,
            "hasRDI": true,
            "daily": 164.61149493333335,
            "unit": "µg"
          },
          {
            "label": "Vitamin C",
            "tag": "VITC",
            "schemaOrgTag": null,
            "total": 117.57014148124998,
            "hasRDI": true,
            "daily": 130.6334905347222,
            "unit": "mg"
          },
          {
            "label": "Thiamin (B1)",
            "tag": "THIA",
            "schemaOrgTag": null,
            "total": 2.5601296387375,
            "hasRDI": true,
            "daily": 213.34413656145833,
            "unit": "mg"
          },
          {
            "label": "Riboflavin (B2)",
            "tag": "RIBF",
            "schemaOrgTag": null,
            "total": 1.5482162499937504,
            "hasRDI": true,
            "daily": 119.09355769182696,
            "unit": "mg"
          },
          {
            "label": "Niacin (B3)",
            "tag": "NIA",
            "schemaOrgTag": null,
            "total": 77.46606572862501,
            "hasRDI": true,
            "daily": 484.1629108039063,
            "unit": "mg"
          },
          {
            "label": "Vitamin B6",
            "tag": "VITB6A",
            "schemaOrgTag": null,
            "total": 4.28448316695,
            "hasRDI": true,
            "daily": 329.5756282269231,
            "unit": "mg"
          },
          {
            "label": "Folate equivalent (total)",
            "tag": "FOLDFE",
            "schemaOrgTag": null,
            "total": 1339.9359228437504,
            "hasRDI": true,
            "daily": 334.9839807109376,
            "unit": "µg"
          },
          {
            "label": "Folate (food)",
            "tag": "FOLFD",
            "schemaOrgTag": null,
            "total": 1339.9359228437504,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Folic acid",
            "tag": "FOLAC",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Vitamin B12",
            "tag": "VITB12",
            "schemaOrgTag": null,
            "total": 63.69503180000001,
            "hasRDI": true,
            "daily": 2653.9596583333337,
            "unit": "µg"
          },
          {
            "label": "Vitamin D",
            "tag": "VITD",
            "schemaOrgTag": null,
            "total": 2.301,
            "hasRDI": true,
            "daily": 15.340000000000002,
            "unit": "µg"
          },
          {
            "label": "Vitamin E",
            "tag": "TOCPHA",
            "schemaOrgTag": null,
            "total": 102.72104695662502,
            "hasRDI": true,
            "daily": 684.8069797108334,
            "unit": "mg"
          },
          {
            "label": "Vitamin K",
            "tag": "VITK1",
            "schemaOrgTag": null,
            "total": 336.55132942250003,
            "hasRDI": true,
            "daily": 280.4594411854167,
            "unit": "µg"
          },
          {
            "label": "Sugar alcohols",
            "tag": "Sugar.alcohol",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          },
          {
            "label": "Water",
            "tag": "WATER",
            "schemaOrgTag": null,
            "total": 3381.784236126188,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          }
        ]
      },
      "_links": {
        "self": {
          "title": "Self",
          "href": "https://api.edamam.com/api/recipes/v2/b4bc51b8a9300f7469afe21fe70207f7?type=public&app_id=60774aad&app_key=4ed5ca518b3756cbc0701d7501264aa8"
        }
      }
    },
    {
      "recipe": {
        "uri": "http://www.edamam.com/ontologies/edamam.owl#recipe_1b0b7c97788a734f3e0dffbb0bfb9791",
        "label": "Crawfish Etouffee",
        "image": "https://edamam-product-images.s3.amazonaws.com/web-img/fd4/fd4c76da3eddd11503b78a32b72b493d.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=46625420bf8aeb7b77bd6ed722bcaf68aa0c15a42f67972612428ce6325dc970",
        "images": {
          "THUMBNAIL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/fd4/fd4c76da3eddd11503b78a32b72b493d-s.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=32428932082aa2d7ee1b2095faf0ddc4dcbc8a593977d8e5a9443713a8b7ecb0",
            "width": 100,
            "height": 100
          },
          "SMALL": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/fd4/fd4c76da3eddd11503b78a32b72b493d-m.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=1a98ede2a40b4367e5219e0140637aeef736e52d292ac690fb8aa4381ff0fe19",
            "width": 200,
            "height": 200
          },
          "REGULAR": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/fd4/fd4c76da3eddd11503b78a32b72b493d.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=46625420bf8aeb7b77bd6ed722bcaf68aa0c15a42f67972612428ce6325dc970",
            "width": 300,
            "height": 300
          },
          "LARGE": {
            "url": "https://edamam-product-images.s3.amazonaws.com/web-img/fd4/fd4c76da3eddd11503b78a32b72b493d-l.jpg?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEEQaCXVzLWVhc3QtMSJGMEQCIEr4drQNLQija0DUCFOtIvwyhGMpIRqwlt6xl4neMtjrAiAvfaQUEKKlSmK%2Bt2hoGwtoO%2B9cj95r4qfMH89H8R0HIyq5BQg9EAAaDDE4NzAxNzE1MDk4NiIM%2FDlgVT2ghyJtin2uKpYFEXk6MlVMu9et46EJUTTC5vgkw3MV5%2BYyjf1PqLAUw4j93ARUgL0%2F5l0kKM%2F9Ik9IH%2BjiTrHaEziCie%2BbzoMNb%2FxVw8cpz9EcpE4nTZv2QwEuVdH1%2FI2vBUWwIy8DRsZGyDEZCtK3UW1jqNscX4Ojyu%2BylmFcQVErIWJ5wNMpv7fVcSazstdpB5tlqJiMn8kCgVj7iehSQrtuuoGKPD3Vc938IZepjLiIg5UbKHSdHF0WPdeOWsV8%2FAIuuzkpCHd6SH%2B76oH%2BgoBzVEskKX7DrxH7MDY4LagJwAQqEHLh23fE4ez9PbiAC1qOqy3tbWygBQqrJdCmtc4up23Z133n2zzJI8nhHVV6WZi5DxqHZuk1MWRw7wfN%2BGLJDJBcPVKB5DGqGZ%2Bclmi%2BncARSNtd7Ddeam2%2FdCD5gPCagWCvucjEJDUSymlI83T6zzlp1PHyl06EoNPTfJJi2Yah%2B1HFAN%2BOkFm7u6lUPBRdT3ALVq8AXOzaSTfDKCburrC2XUu84Cz2WQWgGExw%2B7Enswi3ImdE4yt4bZ4dA2PZYUukwENb6X8HVaXyAmA80Sl5PGD6gifub3FbK8fSnBXPMPMfnDRE5H6gETf%2Baxixm8NDyP0oI0mdhZsA5kbcppi233Ifa9duD82UgR6kpuOpHuaZ0OE0rY7efJX8gNArd6r%2F9Rx5wcnRP9sP%2BUPdW%2BQ7ivl3odUtwotD%2FoU1tF3DZPzzy5%2ByJ0R8Dap3trSWLeNwYHcVxkE0VikC53nVoM2y3lgNgMTZ1bubD6I2LIoCy3cC%2B0soU1TMXfRrRkXkoYpd3ug40ZnhrSlfquaMN3WhdW5vB8QnhOx9wieB0hi4MDyFbfe1cwO%2BnUl2cm2Tl7MwikvstIWIiFIw0ofzoQY6sgGT1tG2cs2hxDbahs0FjKr7UUHTCYsoEdnJq4nPWH2kUGaVXHfVMVM7ycR8Xx7Tp2rgRt2iwDi7BF850dFN3sIg6i0G3oBdKoJ%2FxEP3WB%2BgfKDDlNwHQ3JHymb9cWYXOKNa4jy6xMI2%2BXZFXvHpp01LIzKu3x7PMhYUv0W9nDoedq98i1vltdxY64ujs9nNRmE%2FNCyPm4XxP%2FW6zrH7DbFDg0zDKM3mn%2B2wpLPaZXocGiyr&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230417T045333Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIASXCYXIIFGXJUB24I%2F20230417%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=167f9188b2437e5b99e564e2224992b2adb99cdbdbba4ad7d7500e9f191a073b",
            "width": 600,
            "height": 600
          }
        },
        "source": "geauxaskalice.com",
        "url": "http://geauxaskalice.com/2012/02/crawfish-etouffee/",
        "shareAs": "http://www.edamam.com/recipe/crawfish-etouffee-1b0b7c97788a734f3e0dffbb0bfb9791/crawfish+etouffee/5-8-ing/high-protein/100-300-cal",
        "yield": 14,
        "dietLabels": [
          "High-Protein",
          "Low-Carb"
        ],
        "healthLabels": [
          "Sugar-Conscious",
          "Keto-Friendly",
          "Pescatarian",
          "Egg-Free",
          "Peanut-Free",
          "Tree-Nut-Free",
          "Soy-Free",
          "Fish-Free",
          "Pork-Free",
          "Red-Meat-Free",
          "Mustard-Free",
          "Sesame-Free",
          "Lupine-Free",
          "Mollusk-Free",
          "Alcohol-Free",
          "Sulfite-Free"
        ],
        "cautions": [
          "Sulfites"
        ],
        "ingredientLines": [
          "* 6-8 lb crawfish tail",
          "* 1 stick butter",
          "* 2-16 oz container of pre chopped onion mixture",
          "* 1 tbsp minced garlic",
          "* 1 small can tomato paste",
          "* 1 can cream of mushroom soup",
          "* 1 can of celery soup",
          "* 1 bunch chopped green onion"
        ],
        "ingredients": [
          {
            "text": "* 6-8 lb crawfish tail",
            "quantity": 7,
            "measure": "pound",
            "food": "crawfish",
            "weight": 3175.1465900000003,
            "foodCategory": "seafood",
            "foodId": "food_as9lwx2a9gc0lgb6rwtk5afip7ot",
            "image": "https://www.edamam.com/food-img/3cf/3cf27bacbfc6b38f999fbe2bb2840d8f.jpg"
          },
          {
            "text": "* 1 stick butter",
            "quantity": 1,
            "measure": "stick",
            "food": "butter",
            "weight": 113,
            "foodCategory": "Dairy",
            "foodId": "food_awz3iefajbk1fwahq9logahmgltj",
            "image": "https://www.edamam.com/food-img/713/71397239b670d88c04faa8d05035cab4.jpg"
          },
          {
            "text": "* 2-16 oz container of pre chopped onion mixture",
            "quantity": 9,
            "measure": "ounce",
            "food": "onion",
            "weight": 255.145708125,
            "foodCategory": "vegetables",
            "foodId": "food_bmrvi4ob4binw9a5m7l07amlfcoy",
            "image": "https://www.edamam.com/food-img/205/205e6bf2399b85d34741892ef91cc603.jpg"
          },
          {
            "text": "* 1 tbsp minced garlic",
            "quantity": 1,
            "measure": "tablespoon",
            "food": "garlic",
            "weight": 8.499999999856291,
            "foodCategory": "vegetables",
            "foodId": "food_avtcmx6bgjv1jvay6s6stan8dnyp",
            "image": "https://www.edamam.com/food-img/6ee/6ee142951f48aaf94f4312409f8d133d.jpg"
          },
          {
            "text": "* 1 small can tomato paste",
            "quantity": 1,
            "measure": "can",
            "food": "tomato paste",
            "weight": 170,
            "foodCategory": "canned vegetables",
            "foodId": "food_auu2atfal07b6gbd1a5wsawy7u0s",
            "image": "https://www.edamam.com/food-img/aef/aef4e029118da71388e526086506053a.jpg"
          },
          {
            "text": "* 1 can cream of mushroom soup",
            "quantity": 1,
            "measure": "can",
            "food": "cream of mushroom soup",
            "weight": 303,
            "foodCategory": "canned soup",
            "foodId": "food_b628l7bbpw7rnqa1ri8egb0xetpn",
            "image": "https://www.edamam.com/food-img/545/545d0db4311588977bed0aabfa530c58.jpg"
          },
          {
            "text": "* 1 can of celery soup",
            "quantity": 1,
            "measure": "<unit>",
            "food": "celery",
            "weight": 40,
            "foodCategory": "vegetables",
            "foodId": "food_bffeoksbyyur8ja4da73ub2xs57g",
            "image": "https://www.edamam.com/food-img/d91/d91d2aed1c36d8fad54c4d7dc58f5a18.jpg"
          },
          {
            "text": "* 1 bunch chopped green onion",
            "quantity": 1,
            "measure": "bunch",
            "food": "green onion",
            "weight": 113,
            "foodCategory": "vegetables",
            "foodId": "food_bknlkyzbuzo27pb11whr4bttkuy6",
            "image": "https://www.edamam.com/food-img/b89/b89986ed6aa466285bdd99bac34b3c46.jpg"
          }
        ],
        "calories": 3791.126157549786,
        "totalWeight": 4177.792298124857,
        "totalTime": 0,
        "cuisineType": [
          "french"
        ],
        "mealType": [
          "lunch/dinner"
        ],
        "dishType": [
          "starter"
        ],
        "totalNutrients": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 3791.1261575497856,
            "unit": "kcal"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 139.2565383131243,
            "unit": "g"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 66.35292927551238,
            "unit": "g"
          },
          "FATRN": {
            "label": "Trans",
            "quantity": 3.7738300000000002,
            "unit": "g"
          },
          "FAMS": {
            "label": "Monounsaturated",
            "quantity": 33.16336900865624,
            "unit": "g"
          },
          "FAPU": {
            "label": "Polyunsaturated",
            "quantity": 21.981859279080894,
            "unit": "g"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 88.94170913882749,
            "unit": "g"
          },
          "CHOCDF.net": {
            "label": "Carbohydrates (net)",
            "quantity": 71.7567321007055,
            "unit": "g"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 17.184977038121982,
            "unit": "g"
          },
          "SUGAR": {
            "label": "Sugars",
            "quantity": 36.05787802449857,
            "unit": "g"
          },
          "SUGAR.added": {
            "label": "Sugars, added",
            "quantity": 0,
            "unit": "g"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 525.1570132123659,
            "unit": "g"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 3862.6171126000004,
            "unit": "mg"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 5352.475850524976,
            "unit": "mg"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 1153.3980921684902,
            "unit": "mg"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 994.6791501124642,
            "unit": "mg"
          },
          "K": {
            "label": "Potassium",
            "quantity": 12356.260435661925,
            "unit": "mg"
          },
          "FE": {
            "label": "Iron",
            "quantity": 34.73793734306006,
            "unit": "mg"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 43.80795337381084,
            "unit": "mg"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 8507.722525756031,
            "unit": "mg"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 1481.5034544,
            "unit": "µg"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 119.34854148120516,
            "unit": "mg"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 2.571529638737213,
            "unit": "mg"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 1.5544862499935923,
            "unit": "mg"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 77.505965728624,
            "unit": "mg"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 4.354878166948225,
            "unit": "mg"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 1340.1069228437461,
            "unit": "µg"
          },
          "FOLFD": {
            "label": "Folate (food)",
            "quantity": 1340.1069228437461,
            "unit": "µg"
          },
          "FOLAC": {
            "label": "Folic acid",
            "quantity": 0,
            "unit": "µg"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 63.69503180000001,
            "unit": "µg"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 2.301,
            "unit": "µg"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 102.7256069566249,
            "unit": "mg"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 336.6482294224976,
            "unit": "µg"
          },
          "Sugar.alcohol": {
            "label": "Sugar alcohol",
            "quantity": 0,
            "unit": "g"
          },
          "WATER": {
            "label": "Water",
            "quantity": 3385.1232961261035,
            "unit": "g"
          }
        },
        "totalDaily": {
          "ENERC_KCAL": {
            "label": "Energy",
            "quantity": 189.55630787748927,
            "unit": "%"
          },
          "FAT": {
            "label": "Fat",
            "quantity": 214.2408281740374,
            "unit": "%"
          },
          "FASAT": {
            "label": "Saturated",
            "quantity": 331.7646463775619,
            "unit": "%"
          },
          "CHOCDF": {
            "label": "Carbs",
            "quantity": 29.64723637960917,
            "unit": "%"
          },
          "FIBTG": {
            "label": "Fiber",
            "quantity": 68.73990815248793,
            "unit": "%"
          },
          "PROCNT": {
            "label": "Protein",
            "quantity": 1050.3140264247318,
            "unit": "%"
          },
          "CHOLE": {
            "label": "Cholesterol",
            "quantity": 1287.5390375333334,
            "unit": "%"
          },
          "NA": {
            "label": "Sodium",
            "quantity": 223.01982710520733,
            "unit": "%"
          },
          "CA": {
            "label": "Calcium",
            "quantity": 115.339809216849,
            "unit": "%"
          },
          "MG": {
            "label": "Magnesium",
            "quantity": 236.82836907439622,
            "unit": "%"
          },
          "K": {
            "label": "Potassium",
            "quantity": 262.89915820557286,
            "unit": "%"
          },
          "FE": {
            "label": "Iron",
            "quantity": 192.98854079477812,
            "unit": "%"
          },
          "ZN": {
            "label": "Zinc",
            "quantity": 398.25412158009857,
            "unit": "%"
          },
          "P": {
            "label": "Phosphorus",
            "quantity": 1215.3889322508614,
            "unit": "%"
          },
          "VITA_RAE": {
            "label": "Vitamin A",
            "quantity": 164.61149493333335,
            "unit": "%"
          },
          "VITC": {
            "label": "Vitamin C",
            "quantity": 132.6094905346724,
            "unit": "%"
          },
          "THIA": {
            "label": "Thiamin (B1)",
            "quantity": 214.29413656143439,
            "unit": "%"
          },
          "RIBF": {
            "label": "Riboflavin (B2)",
            "quantity": 119.57586538412248,
            "unit": "%"
          },
          "NIA": {
            "label": "Niacin (B3)",
            "quantity": 484.41228580390003,
            "unit": "%"
          },
          "VITB6A": {
            "label": "Vitamin B6",
            "quantity": 334.99062822678655,
            "unit": "%"
          },
          "FOLDFE": {
            "label": "Folate equivalent (total)",
            "quantity": 335.02673071093653,
            "unit": "%"
          },
          "VITB12": {
            "label": "Vitamin B12",
            "quantity": 2653.9596583333337,
            "unit": "%"
          },
          "VITD": {
            "label": "Vitamin D",
            "quantity": 15.340000000000002,
            "unit": "%"
          },
          "TOCPHA": {
            "label": "Vitamin E",
            "quantity": 684.8373797108327,
            "unit": "%"
          },
          "VITK1": {
            "label": "Vitamin K",
            "quantity": 280.5401911854147,
            "unit": "%"
          }
        },
        "digest": [
          {
            "label": "Fat",
            "tag": "FAT",
            "schemaOrgTag": "fatContent",
            "total": 139.2565383131243,
            "hasRDI": true,
            "daily": 214.2408281740374,
            "unit": "g",
            "sub": [
              {
                "label": "Saturated",
                "tag": "FASAT",
                "schemaOrgTag": "saturatedFatContent",
                "total": 66.35292927551238,
                "hasRDI": true,
                "daily": 331.7646463775619,
                "unit": "g"
              },
              {
                "label": "Trans",
                "tag": "FATRN",
                "schemaOrgTag": "transFatContent",
                "total": 3.7738300000000002,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Monounsaturated",
                "tag": "FAMS",
                "schemaOrgTag": null,
                "total": 33.16336900865624,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Polyunsaturated",
                "tag": "FAPU",
                "schemaOrgTag": null,
                "total": 21.981859279080894,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Carbs",
            "tag": "CHOCDF",
            "schemaOrgTag": "carbohydrateContent",
            "total": 88.94170913882749,
            "hasRDI": true,
            "daily": 29.64723637960917,
            "unit": "g",
            "sub": [
              {
                "label": "Carbs (net)",
                "tag": "CHOCDF.net",
                "schemaOrgTag": null,
                "total": 71.7567321007055,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Fiber",
                "tag": "FIBTG",
                "schemaOrgTag": "fiberContent",
                "total": 17.184977038121982,
                "hasRDI": true,
                "daily": 68.73990815248793,
                "unit": "g"
              },
              {
                "label": "Sugars",
                "tag": "SUGAR",
                "schemaOrgTag": "sugarContent",
                "total": 36.05787802449857,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              },
              {
                "label": "Sugars, added",
                "tag": "SUGAR.added",
                "schemaOrgTag": null,
                "total": 0,
                "hasRDI": false,
                "daily": 0,
                "unit": "g"
              }
            ]
          },
          {
            "label": "Protein",
            "tag": "PROCNT",
            "schemaOrgTag": "proteinContent",
            "total": 525.1570132123659,
            "hasRDI": true,
            "daily": 1050.3140264247318,
            "unit": "g"
          },
          {
            "label": "Cholesterol",
            "tag": "CHOLE",
            "schemaOrgTag": "cholesterolContent",
            "total": 3862.6171126000004,
            "hasRDI": true,
            "daily": 1287.5390375333334,
            "unit": "mg"
          },
          {
            "label": "Sodium",
            "tag": "NA",
            "schemaOrgTag": "sodiumContent",
            "total": 5352.475850524976,
            "hasRDI": true,
            "daily": 223.01982710520733,
            "unit": "mg"
          },
          {
            "label": "Calcium",
            "tag": "CA",
            "schemaOrgTag": null,
            "total": 1153.3980921684902,
            "hasRDI": true,
            "daily": 115.339809216849,
            "unit": "mg"
          },
          {
            "label": "Magnesium",
            "tag": "MG",
            "schemaOrgTag": null,
            "total": 994.6791501124642,
            "hasRDI": true,
            "daily": 236.82836907439622,
            "unit": "mg"
          },
          {
            "label": "Potassium",
            "tag": "K",
            "schemaOrgTag": null,
            "total": 12356.260435661925,
            "hasRDI": true,
            "daily": 262.89915820557286,
            "unit": "mg"
          },
          {
            "label": "Iron",
            "tag": "FE",
            "schemaOrgTag": null,
            "total": 34.73793734306006,
            "hasRDI": true,
            "daily": 192.98854079477812,
            "unit": "mg"
          },
          {
            "label": "Zinc",
            "tag": "ZN",
            "schemaOrgTag": null,
            "total": 43.80795337381084,
            "hasRDI": true,
            "daily": 398.25412158009857,
            "unit": "mg"
          },
          {
            "label": "Phosphorus",
            "tag": "P",
            "schemaOrgTag": null,
            "total": 8507.722525756031,
            "hasRDI": true,
            "daily": 1215.3889322508614,
            "unit": "mg"
          },
          {
            "label": "Vitamin A",
            "tag": "VITA_RAE",
            "schemaOrgTag": null,
            "total": 1481.5034544,
            "hasRDI": true,
            "daily": 164.61149493333335,
            "unit": "µg"
          },
          {
            "label": "Vitamin C",
            "tag": "VITC",
            "schemaOrgTag": null,
            "total": 119.34854148120516,
            "hasRDI": true,
            "daily": 132.6094905346724,
            "unit": "mg"
          },
          {
            "label": "Thiamin (B1)",
            "tag": "THIA",
            "schemaOrgTag": null,
            "total": 2.571529638737213,
            "hasRDI": true,
            "daily": 214.29413656143439,
            "unit": "mg"
          },
          {
            "label": "Riboflavin (B2)",
            "tag": "RIBF",
            "schemaOrgTag": null,
            "total": 1.5544862499935923,
            "hasRDI": true,
            "daily": 119.57586538412248,
            "unit": "mg"
          },
          {
            "label": "Niacin (B3)",
            "tag": "NIA",
            "schemaOrgTag": null,
            "total": 77.505965728624,
            "hasRDI": true,
            "daily": 484.41228580390003,
            "unit": "mg"
          },
          {
            "label": "Vitamin B6",
            "tag": "VITB6A",
            "schemaOrgTag": null,
            "total": 4.354878166948225,
            "hasRDI": true,
            "daily": 334.99062822678655,
            "unit": "mg"
          },
          {
            "label": "Folate equivalent (total)",
            "tag": "FOLDFE",
            "schemaOrgTag": null,
            "total": 1340.1069228437461,
            "hasRDI": true,
            "daily": 335.02673071093653,
            "unit": "µg"
          },
          {
            "label": "Folate (food)",
            "tag": "FOLFD",
            "schemaOrgTag": null,
            "total": 1340.1069228437461,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Folic acid",
            "tag": "FOLAC",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "µg"
          },
          {
            "label": "Vitamin B12",
            "tag": "VITB12",
            "schemaOrgTag": null,
            "total": 63.69503180000001,
            "hasRDI": true,
            "daily": 2653.9596583333337,
            "unit": "µg"
          },
          {
            "label": "Vitamin D",
            "tag": "VITD",
            "schemaOrgTag": null,
            "total": 2.301,
            "hasRDI": true,
            "daily": 15.340000000000002,
            "unit": "µg"
          },
          {
            "label": "Vitamin E",
            "tag": "TOCPHA",
            "schemaOrgTag": null,
            "total": 102.7256069566249,
            "hasRDI": true,
            "daily": 684.8373797108327,
            "unit": "mg"
          },
          {
            "label": "Vitamin K",
            "tag": "VITK1",
            "schemaOrgTag": null,
            "total": 336.6482294224976,
            "hasRDI": true,
            "daily": 280.5401911854147,
            "unit": "µg"
          },
          {
            "label": "Sugar alcohols",
            "tag": "Sugar.alcohol",
            "schemaOrgTag": null,
            "total": 0,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          },
          {
            "label": "Water",
            "tag": "WATER",
            "schemaOrgTag": null,
            "total": 3385.1232961261035,
            "hasRDI": false,
            "daily": 0,
            "unit": "g"
          }
        ]
      },
      "_links": {
        "self": {
          "title": "Self",
          "href": "https://api.edamam.com/api/recipes/v2/1b0b7c97788a734f3e0dffbb0bfb9791?type=public&app_id=60774aad&app_key=4ed5ca518b3756cbc0701d7501264aa8"
        }
      }
    }
  ]
}

"""
